/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class StringRead */

#ifndef _Included_StringRead
#define _Included_StringRead
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     StringRead
 * Method:    Read
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_StringRead_Read
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif

