/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AShell_CallSystem */

#ifndef _Included_AShell_CallSystem
#define _Included_AShell_CallSystem
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AShell_CallSystem
 * Method:    System
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT jint JNICALL Java_AShell_CallSystem_System(JNIEnv *, jclass, jstring);
JNIEXPORT jint JNICALL Java_AShell_CallSystem_chdir(JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
