/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CFunction */

#ifndef _Included_CFunction
#define _Included_CFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CFunction
 * Method:    clearScreen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CFunction_clearScreen
  (JNIEnv *, jclass);

/*
 * Class:     CFunction
 * Method:    Cgetch
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_CFunction_Cgetch
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif


